name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09b48fdcb5b40b84bf59e25ab87524cc30612426d9aeca632f6926099db5a932"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
