name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5572ba7b8f77d5e0c98fb58846725bdc945b004d750949430213cbb6c189eaee"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
