name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52e827fd93b41d531f8c20124b59fb380b282ebdbbcfa92e0ea01ba21ffe7b0f"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
