name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "236800653142327d3ddd187710f7e090fd8a1cb34c907879a0e07ab36fe1e4f1"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
