name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b156e8ab0b4fcd5b8b11a8b96635a43cf1f6584f35332bfc85c246b4148248b4"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
