name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc773221143307e8ae81f3c5a1850f33bdd3d1f661ff0e1febb0c66f81da549d"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
