name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7580abcd5995914da1aaac28ad7591d332b7c2522ab89e58a8e770e34c6bb1a9"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
