name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9549bfc329e48ad29578b1e9976b846b39321fbfac057767609b954e1d037139"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
