name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b82da203a278c12a212a5cbcc928d1d8fdd958102a33a6bfeb6d3f9b6b64a3c"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
