name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c0f579e4e43d6c695991390cefe8a5b88478be429e485ca08b8d7d4cc6f4a54"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
