name = "Pug's Pixelmon"
author = "MerchantPug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2591f989b294bd7766c98022ee1201e3a0dce95e7336662eb4860273bb1f44"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
